language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

env:
    - DOCTRINE_VERSION=2.3.*
    - DOCTRINE_VERSION=2.4.*
    - DOCTRINE_VERSION=2.5.*
    - DOCTRINE_VERSION=dev-master

before_script:
    - composer self-update
    - composer require doctrine/orm:${DOCTRINE_VERSION} --no-update
    - composer update --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - bash <(curl -s https://codecov.io/bash)